using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PickupItem : MonoBehaviour
{
    public SESoundManager SESoundManager;
    //@‰ñ“]‚Ì‘¬“x
    public float Rollspeed = 0.2f;

    private void Update()
    {
        // (0,1,0)
        this.gameObject.transform.Rotate(Vector3.up * Rollspeed, Space.World);
    }

    // Õ“Ë”»’è‚ğæ“¾‚µ‚Ü‚·
    private void OnCollisionEnter(Collision collision)
    {
        //@‚à‚µÕ“Ë‚µ‚Ä‚«‚½‚Ì‚ªPlayer‚¾‚Á‚½‚ç
        if (collision.gameObject.tag.Equals("Player"))
        {
            SESoundManager.PlayPickupItemSE();
            // ©•ª‚ğÁ‚µ‚Ü‚·
            Destroy(this.gameObject);
        }
    }
}

